import { StyleSheet } from 'react-native';

export const profileStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#090E16' },
  container: { flex: 1, backgroundColor: '#090E16' },
  content: { paddingBottom: 120, paddingHorizontal: 8 },
  achievementToast: {
    alignItems: 'center',
    backgroundColor: '#8B4EF4',
    borderRadius: 16,
    flexDirection: 'row',
    left: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    position: 'absolute',
    right: 16,
    top: 10,
    zIndex: 400,
  },
  achievementToastText: {
    marginLeft: 10,
  },
  achievementToastTitle: {
    color: '#F7F3FF',
    fontSize: 13,
    fontWeight: '800',
  },
  achievementToastSubtitle: {
    color: '#EFE4FF',
    fontSize: 12,
    marginTop: 3,
  },
  feedbackState: { alignItems: 'center', flex: 1, justifyContent: 'center', paddingHorizontal: 24 },
  feedbackTitle: { color: '#F5F7FB', fontSize: 24, fontWeight: '700', marginTop: 18 },
  feedbackText: { color: '#97A0AE', fontSize: 14, lineHeight: 22, marginTop: 12, textAlign: 'center' },
  feedbackError: { color: '#C7CDD7', fontSize: 13, marginTop: 14, textAlign: 'center' },
  retryButton: {
    backgroundColor: '#8B4EF4',
    borderRadius: 12,
    marginTop: 24,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  retryButtonText: { color: '#F7F3FF', fontSize: 14, fontWeight: '700' },
  topBar: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 18,
    marginTop: 8,
    paddingHorizontal: 8,
    zIndex: 200,
    elevation: 20,
  },
  screenTitle: { color: '#F5F7FB', fontSize: 30, fontWeight: '800' },
  settingsWrap: { position: 'relative', zIndex: 250, elevation: 24 },
  settingsButton: {
    alignItems: 'center',
    backgroundColor: '#141B26',
    borderColor: '#202938',
    borderRadius: 16,
    borderWidth: 1,
    height: 46,
    justifyContent: 'center',
    width: 46,
  },
  settingsMenu: {
    backgroundColor: '#141B26',
    borderColor: '#202938',
    borderRadius: 16,
    borderWidth: 1,
    padding: 8,
    position: 'absolute',
    right: 0,
    top: 54,
    width: 150,
    zIndex: 300,
    elevation: 30,
  },
  settingsMenuItem: { alignItems: 'center', flexDirection: 'row', gap: 10, paddingHorizontal: 10, paddingVertical: 10 },
  settingsMenuText: { color: '#F7F3FF', fontSize: 14, fontWeight: '700' },
  settingsMenuDangerText: { color: '#FF8C8C', fontSize: 14, fontWeight: '700' },
  levelUpBackdrop: {
    alignItems: 'center',
    backgroundColor: 'rgba(7, 10, 16, 0.7)',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  levelUpCard: {
    alignItems: 'center',
    backgroundColor: '#141B26',
    borderColor: '#8B4EF4',
    borderRadius: 28,
    borderWidth: 1,
    overflow: 'hidden',
    paddingHorizontal: 24,
    paddingVertical: 28,
    width: '100%',
  },
  levelUpGlow: {
    backgroundColor: '#A866FF',
    borderRadius: 120,
    height: 120,
    opacity: 0.18,
    position: 'absolute',
    top: -20,
    width: 120,
  },
  levelUpEyebrow: {
    color: '#C9A9FF',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.6,
    marginTop: 14,
  },
  levelUpTitle: {
    color: '#F7F3FF',
    fontSize: 34,
    fontWeight: '900',
    marginTop: 10,
  },
  levelUpText: {
    color: '#C7D0DB',
    fontSize: 14,
    lineHeight: 22,
    marginTop: 10,
    textAlign: 'center',
  },
  levelUpButton: {
    backgroundColor: '#8B4EF4',
    borderRadius: 14,
    marginTop: 22,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  levelUpButtonText: {
    color: '#F7F3FF',
    fontSize: 14,
    fontWeight: '800',
  },
  heroCard: {
    backgroundColor: '#141B26',
    borderColor: '#202938',
    borderRadius: 26,
    borderWidth: 1,
    marginHorizontal: 8,
    marginTop: 4,
    padding: 18,
  },
  heroTop: { flexDirection: 'row', gap: 16 },
  avatarWrap: { alignItems: 'center', justifyContent: 'center' },
  avatarOuter: {
    alignItems: 'center',
    backgroundColor: '#8B4EF4',
    borderRadius: 42,
    height: 84,
    justifyContent: 'center',
    padding: 3,
    width: 84,
  },
  avatarInner: { alignItems: 'center', backgroundColor: '#D4B5FF', borderRadius: 39, flex: 1, justifyContent: 'center', width: '100%' },
  levelBadge: {
    backgroundColor: '#131A25',
    borderColor: '#8B4EF4',
    borderRadius: 14,
    borderWidth: 2,
    paddingHorizontal: 8,
    paddingVertical: 4,
    position: 'absolute',
    right: -4,
    top: 58,
  },
  levelBadgeText: { color: '#F7F3FF', fontSize: 13, fontWeight: '800' },
  heroInfo: { flex: 1 },
  name: { color: '#F5F7FB', fontSize: 24, fontWeight: '800' },
  tagline: { color: '#97A0AE', fontSize: 13, lineHeight: 20, marginTop: 6 },
  levelRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 16 },
  levelText: { color: '#B77BFF', fontSize: 13, fontWeight: '700' },
  xpText: { color: '#C8D0DA', fontSize: 12, fontWeight: '700' },
  largeProgressTrack: { backgroundColor: '#2A3342', borderRadius: 999, height: 9, marginTop: 8, overflow: 'hidden' },
  largeProgressFill: { backgroundColor: '#A866FF', borderRadius: 999, height: '100%' },
  levelHint: { color: '#9AA3B2', fontSize: 12, marginTop: 8 },
  streakRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 14 },
  streakPill: {
    alignItems: 'center',
    backgroundColor: '#1A2230',
    borderRadius: 999,
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  streakPillText: { color: '#F5F7FB', fontSize: 12, fontWeight: '700' },
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 14, paddingHorizontal: 8 },
  categoryLevelRow: { gap: 14, paddingTop: 4 },
  categoryLevelCard: {
    backgroundColor: '#182130',
    borderColor: '#263245',
    borderRadius: 22,
    borderWidth: 1,
    minWidth: 150,
    padding: 16,
    width: 150,
  },
  statCard: {
    backgroundColor: '#141B26',
    borderColor: '#202938',
    borderRadius: 18,
    borderWidth: 1,
    minWidth: '47%',
    padding: 14,
    width: '47%',
  },
  statHeaderRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  statIconWrap: {
    alignItems: 'center',
    borderRadius: 12,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  statLevelChip: {
    backgroundColor: '#111824',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  statLevelChipText: {
    fontSize: 11,
    fontWeight: '800',
  },
  statTitle: { color: '#F5F7FB', fontSize: 15, fontWeight: '700', marginTop: 10 },
  statLevel: { color: '#B1BAC9', fontSize: 12, marginTop: 4 },
  categoryLevelValue: { fontSize: 14, fontWeight: '800', marginTop: 10 },
  smallProgressTrack: { backgroundColor: '#2A3342', borderRadius: 999, height: 6, marginTop: 10, overflow: 'hidden' },
  smallProgressFill: { borderRadius: 999, height: '100%' },
  statProgress: { color: '#9AA3B2', fontSize: 11, marginTop: 8 },
  sectionCard: {
    backgroundColor: '#141B26',
    borderColor: '#202938',
    borderRadius: 22,
    borderWidth: 1,
    marginHorizontal: 8,
    marginTop: 14,
    padding: 16,
  },
  sectionHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12 },
  sectionTitle: { color: '#F5F7FB', fontSize: 19, fontWeight: '800' },
  sectionAction: { alignItems: 'center', flexDirection: 'row', gap: 4 },
  sectionActionText: { color: '#8D56F7', fontSize: 13, fontWeight: '700' },
  xpEntryRow: { alignItems: 'center', flexDirection: 'row', gap: 12, paddingVertical: 12 },
  xpEntryText: { flex: 1 },
  xpEntryTitle: { color: '#F5F7FB', fontSize: 15, fontWeight: '700' },
  xpEntryDescription: { color: '#97A0AE', fontSize: 12, lineHeight: 18, marginTop: 4 },
  xpEntryValue: { color: '#A866FF', fontSize: 14, fontWeight: '800' },
  rowBorder: { borderBottomColor: '#1F2837', borderBottomWidth: 1 },
  goalRow: { flexDirection: 'row', gap: 12, paddingVertical: 12 },
  goalIconWrap: { alignItems: 'center', borderRadius: 14, height: 44, justifyContent: 'center', width: 44 },
  goalContent: { flex: 1 },
  goalTitleRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  goalTitle: { color: '#F5F7FB', fontSize: 16, fontWeight: '700' },
  goalSubtitle: { color: '#97A0AE', fontSize: 13, marginTop: 4 },
  goalProgressRow: { alignItems: 'center', flexDirection: 'row', gap: 10, marginTop: 10 },
  goalProgressTrack: { backgroundColor: '#2A3342', borderRadius: 999, flex: 1, height: 6, overflow: 'hidden' },
  goalProgressFill: { borderRadius: 999, height: '100%' },
  goalPercent: { color: '#C9D1DA', fontSize: 12, fontWeight: '700' },
  questRow: { alignItems: 'center', flexDirection: 'row', gap: 12, paddingVertical: 12 },
  questTextWrap: { flex: 1 },
  questTitle: { color: '#F5F7FB', fontSize: 15, fontWeight: '700' },
  questSubtitle: { color: '#97A0AE', fontSize: 12, marginTop: 4 },
  questXp: { color: '#D7BCFF', fontSize: 13, fontWeight: '800' },
  questSummaryRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 14 },
  summaryPill: { backgroundColor: '#1A2230', borderRadius: 999, paddingHorizontal: 12, paddingVertical: 8 },
  summaryPillText: { color: '#DCE2EA', fontSize: 12, fontWeight: '700' },
  achievementRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  achievementCard: { minWidth: '31%', width: '31%' },
  achievementIconWrap: {
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 2,
    height: 64,
    justifyContent: 'center',
    width: 64,
  },
  achievementTitle: { color: '#F5F7FB', fontSize: 14, fontWeight: '700', marginTop: 10 },
  achievementSubtitle: { color: '#97A0AE', fontSize: 12, lineHeight: 18, marginTop: 6 },
  achievementRarity: { color: '#B77BFF', fontSize: 11, fontWeight: '800', marginTop: 6 },
  weeklyStatsRow: { flexDirection: 'row', flexWrap: 'wrap' },
  weeklyStatCard: { minWidth: '25%', paddingHorizontal: 8, width: '25%' },
  weeklyStatDivider: { borderRightColor: '#1F2837', borderRightWidth: 1 },
  weeklyValue: { color: '#F5F7FB', fontSize: 28, fontWeight: '800', marginTop: 10 },
  weeklyLabel: { color: '#D7DEE7', fontSize: 13, fontWeight: '700', marginTop: 8 },
  weeklyDetail: { color: '#97A0AE', fontSize: 11, lineHeight: 16, marginTop: 8 },
  categoryModalBackdrop: {
    alignItems: 'center',
    backgroundColor: 'rgba(7, 10, 16, 0.72)',
    flex: 1,
    justifyContent: 'center',
    padding: 20,
  },
  categoryModalCard: {
    backgroundColor: '#121925',
    borderColor: '#242D3D',
    borderRadius: 24,
    borderWidth: 1,
    maxHeight: '82%',
    padding: 18,
    width: '100%',
  },
  categoryModalHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  categoryModalTitle: { color: '#F5F7FB', fontSize: 22, fontWeight: '800' },
  categoryModalCloseButton: {
    alignItems: 'center',
    backgroundColor: '#1B2432',
    borderRadius: 14,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  categoryHistoryCard: {
    backgroundColor: '#182130',
    borderColor: '#263245',
    borderRadius: 20,
    borderWidth: 1,
    marginBottom: 14,
    padding: 16,
  },
  categoryHistoryHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  categoryHistoryCopy: { flex: 1 },
  categoryHistoryTitle: { color: '#F5F7FB', fontSize: 16, fontWeight: '800' },
  categoryHistoryLevel: { fontSize: 13, fontWeight: '800', marginTop: 4 },
  categoryHistoryXp: { color: '#C9D1DA', fontSize: 12, fontWeight: '700' },
  categoryHistoryList: { marginTop: 12 },
  categoryHistoryEntry: {
    alignItems: 'center',
    borderTopColor: '#253044',
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    paddingVertical: 10,
  },
  categoryHistoryEntryCopy: { flex: 1 },
  categoryHistoryEntryTitle: { color: '#F5F7FB', fontSize: 13, fontWeight: '700' },
  categoryHistoryEntryDescription: { color: '#97A0AE', fontSize: 12, marginTop: 4 },
  categoryHistoryEntryXp: { color: '#C9A9FF', fontSize: 13, fontWeight: '800' },
  categoryHistoryEmpty: { color: '#97A0AE', fontSize: 12, marginTop: 12 },
  deleteAccountCard: {
    backgroundColor: '#121925',
    borderColor: '#4B2626',
    borderRadius: 24,
    borderWidth: 1,
    padding: 20,
    width: '100%',
  },
  deleteAccountTitle: { color: '#F5F7FB', fontSize: 22, fontWeight: '800' },
  deleteAccountText: { color: '#C3CBD7', fontSize: 14, lineHeight: 22, marginTop: 10 },
  deleteAccountActions: { flexDirection: 'row', gap: 12, justifyContent: 'flex-end', marginTop: 20 },
  deleteAccountSecondaryButton: {
    backgroundColor: '#1B2432',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  deleteAccountSecondaryText: { color: '#D9E0EA', fontSize: 14, fontWeight: '700' },
  deleteAccountPrimaryButton: {
    backgroundColor: '#A33A3A',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  deleteAccountPrimaryText: { color: '#FFF3F3', fontSize: 14, fontWeight: '800' },
});
