import { CATEGORY_COLORS, type GoalTemplateSeed } from '../template-seed-types';

export const learningGoalTemplates: GoalTemplateSeed[] = [
  {
    title: 'Klara en kurs',
    icon: 'school-outline',
    subtitle: ['learning'],
    summaryDescription: 'Följ en plan och klara din kurs med bra resultat.',
    category: 'STUDY',
    difficulty: 'MEDIUM',
    focusLabel: 'Studieplan, veckomål och examination',
    totalXpReward: 700,
    color: CATEGORY_COLORS.learning,
    isPopular: true,
    milestones: [
      { title: 'Gör en studieplan för kursen' },
      { title: 'Dela upp kursen i veckomål' },
      { title: 'Gör alla inlämningar i tid' },
      { title: 'Repetera inför examination' },
      { title: 'Genomför tentan eller slutuppgiften' },
    ],
  },
  {
    title: 'Ta examen',
    icon: 'school-outline',
    subtitle: ['learning'],
    summaryDescription: 'Planera dina studier så att du klarar alla moment innan examen.',
    category: 'STUDY',
    difficulty: 'HARD',
    focusLabel: 'Kurser, deadlines och veckovis uppföljning',
    totalXpReward: 1000,
    color: CATEGORY_COLORS.learning,
    isPopular: false,
    milestones: [
      { title: 'Lista alla kvarvarande kurser och deadlines' },
      { title: 'Planera terminen vecka för vecka' },
      { title: 'Boka studietid i kalendern' },
      { title: 'Slutför uppgifter i förväg' },
      { title: 'Följ upp studieplanen varje vecka' },
    ],
  },
  {
    title: 'Ta körkort',
    icon: 'school-outline',
    subtitle: ['learning'],
    summaryDescription: 'Ta dig steg för steg fram till körkortet.',
    category: 'STUDY',
    difficulty: 'HARD',
    focusLabel: 'Teori, körlektioner och prov',
    totalXpReward: 1200,
    color: CATEGORY_COLORS.learning,
    isPopular: false,
    milestones: [
      { title: 'del 1' },
    ],
  },
];
