import { CATEGORY_COLORS, type GoalTemplateSeed } from '../../template-seed-types';
import { runningSharedQuests } from './training-types';

export const runningGoals: GoalTemplateSeed[] = [
  {
    title: 'Springa 1 km',
    icon: 'walk-outline',
    subtitle: ['running'],
    summaryDescription: 'Kom igång med löpning och klara din första kilometer utan paus.',
    category: 'TRAINING',
    difficulty: 'EASY',
    focusLabel: 'Låg tröskel och första löpvanan',
    totalXpReward: 420,
    color: CATEGORY_COLORS.training,
    isPopular: true,
    milestones: [
      {
        title: 'Kom i gång',
        description: 'Väck kroppen och skapa vana med korta pass.',
        xpReward: 60,
        subtasks: ['Gå 15 minuter utan paus', 'Jogga 30 sekunder åt gången', 'Genomför två korta pass samma vecka'],
        tips: ['Spring långsamt från början.', 'Fokusera på vana före prestation.'],
      },
      {
        title: 'Varva gång och jogg',
        description: 'Öka tiden du joggar successivt.',
        xpReward: 80,
        subtasks: ['Jogga 1 minut och gå 1 minut', 'Upprepa intervaller i 12 minuter', 'Känn efter hur kroppen svarar'],
        tips: ['Det är helt okej att gå mellan intervallerna.', 'Målet är kontinuitet.'],
      },
      {
        title: 'Bygg första uthålligheten',
        description: 'Börja springa längre sammanhängande sträckor.',
        xpReward: 80,
        subtasks: ['Spring 500 meter utan paus', 'Spring 5 minuter sammanhängande', 'Genomför tre lugna pass under en vecka'],
        tips: ['Välj platt underlag i början.', 'Ta det lugnt även om du känner dig stark.'],
      },
      {
        title: 'Spring 1 km',
        description: 'Sätt ihop allt och spring din första kilometer.',
        xpReward: 80,
        subtasks: ['Värm upp med rask gång', 'Spring 1 km utan att stanna', 'Notera hur det kändes efter passet'],
        tips: ['Börja långsammare än du tror.', 'Se första kilometern som ett startskott.'],
      },
    ],
    quests: runningSharedQuests,
  },
  {
    title: 'Springa 5 km',
    icon: 'walk-outline',
    subtitle: ['running'],
    summaryDescription: 'Bygg upp din kondition och spring 5 km utan att stanna.',
    category: 'TRAINING',
    difficulty: 'MEDIUM',
    focusLabel: 'Kondition och uthållighet',
    totalXpReward: 1200,
    color: CATEGORY_COLORS.training,
    isPopular: true,
    milestones: [
      {
        title: 'Startmål',
        description: 'Kom igång lugnt och vänj kroppen vid rörelse.',
        xpReward: 100,
        subtasks: [
          'Gå 20 minuter utan paus',
          'Jogga 1 minut och gå 2 minuter, upprepa 8 gånger',
          'Genomför 2 lugna pass samma vecka',
        ],
        tips: [
          'Spring så långsamt att du kan prata samtidigt.',
          'Det viktigaste är att skapa vanan, inte att springa snabbt.',
        ],
      },
      {
        title: 'Grunduthållighet',
        description: 'Bygg upp konditionen så att du orkar springa längre utan att stanna.',
        xpReward: 200,
        subtasks: [
          'Spring 1 km utan paus',
          'Spring 10 minuter sammanhängande',
          'Genomför 3 träningspass under en vecka',
        ],
        tips: [
          'Varva gång och jogg om det behövs.',
          'Vila minst en dag mellan löppassen i början.',
        ],
      },
      {
        title: 'Bygg mot 5 km',
        description: 'Öka distansen stegvis och hitta ett tempo som känns hållbart.',
        xpReward: 400,
        subtasks: [
          'Spring 2 km utan paus',
          'Spring 3 km utan paus',
          'Spring 20 minuter sammanhängande',
          'Spring totalt 4 km under ett pass',
        ],
        tips: [
          'Öka hellre lite i taget än för mycket på en gång.',
          'Fokusera på att fullfölja passet, inte på hastigheten.',
        ],
      },
      {
        title: 'Nära målet',
        description: 'Ta dig från nästan där till att klara hela fem kilometer.',
        xpReward: 500,
        subtasks: [
          'Spring 4 km utan paus',
          'Spring 30 minuter sammanhängande',
          'Testa 5 km i lugnt tempo',
          'Spring 5 km utan att stanna',
        ],
        tips: [
          'Planera rutten i förväg så att du vet ungefär hur långt du ska springa.',
          'Börja långsammare än du tror att du behöver.',
        ],
      },
    ],
    quests: runningSharedQuests,
  },
  {
    title: 'Springa 10 km',
    icon: 'walk-outline',
    subtitle: ['running'],
    summaryDescription: 'Bygg vidare från 5 km och klara att springa 10 km i ett hållbart tempo.',
    category: 'TRAINING',
    difficulty: 'HARD',
    focusLabel: 'Distansökning, veckovolym och återhämtning',
    totalXpReward: 980,
    color: CATEGORY_COLORS.training,
    isPopular: false,
    milestones: [
      { title: 'Stabilisera 5 km som grund', xpReward: 120, subtasks: ['Spring 5 km två gånger', 'Hitta ett jämnt tempo', 'Återhämta dig bra mellan passen'], tips: ['Pressa inte tempot ännu.', 'Fokusera på trygg bas.'] },
      { title: 'Öka veckovolymen', xpReward: 180, subtasks: ['Lägg till ett extra pass per vecka', 'Öka total distans försiktigt', 'Logga passen du gör'], tips: ['Öka gradvis.', 'Hellre jämnt än snabbt.'] },
      { title: 'Bygg längre pass', xpReward: 220, subtasks: ['Spring 6 km', 'Spring 7 km', 'Spring 8 km i lugnt tempo'], tips: ['Välj ett kontrollerat tempo.', 'Planera återhämtning.'] },
      { title: 'Nå 10 km', xpReward: 220, subtasks: ['Spring 9 km sammanhängande', 'Testa 10 km i lugnt tempo', 'Spring 10 km utan att stanna'], tips: ['Starta lugnt.', 'Ta med vatten om passet blir långt.'] },
    ],
    quests: runningSharedQuests,
  },
  {
    title: 'Springa halvmaraton',
    icon: 'walk-outline',
    subtitle: ['running'],
    summaryDescription: 'Träna stegvis för att kunna genomföra ett halvmaraton.',
    category: 'TRAINING',
    difficulty: 'EPIC',
    focusLabel: 'Långpass, veckovolym och återhämtning',
    totalXpReward: 1200,
    color: CATEGORY_COLORS.training,
    isPopular: false,
    milestones: [
      { title: 'Skapa ett 12-veckors träningsupplägg', xpReward: 100 },
      { title: 'Bygg upp veckovolymen gradvis', xpReward: 150 },
      { title: 'Lägg in ett långpass varje vecka', xpReward: 175 },
      { title: 'Träna tempo och återhämtning', xpReward: 175 },
      { title: 'Genomför loppet', xpReward: 300 },
    ],
    quests: runningSharedQuests,
  },
  {
    title: 'Springa maraton',
    icon: 'walk-outline',
    subtitle: ['running'],
    summaryDescription: 'Bygg upp kroppen och rutinerna för att klara ett helt maraton.',
    category: 'TRAINING',
    difficulty: 'LEGENDARY',
    focusLabel: 'Långsiktigt upplägg, återhämtning och långpass',
    totalXpReward: 1800,
    color: CATEGORY_COLORS.training,
    isPopular: false,
    milestones: [
      { title: 'Sätt ett maratonupplägg', xpReward: 180, subtasks: ['Planera träningsveckor', 'Bestäm tidsram', 'Boka in nyckelpass'], tips: ['Ha marginaler i planen.', 'Utgå från din nuvarande nivå.'] },
      { title: 'Bygg stabil veckovolym', xpReward: 260, subtasks: ['Spring regelbundet varje vecka', 'Öka distans långsamt', 'Följ upp återhämtning'], tips: ['Volym kräver tålamod.', 'Hoppa inte över vila.'] },
      { title: 'Utveckla långpassen', xpReward: 320, subtasks: ['Spring 18 km', 'Spring 24 km', 'Spring 30 km'], tips: ['Långpass ska vara kontrollerade.', 'Testa energi och vätska.'] },
      { title: 'Träna fart och uthållighet', xpReward: 240, subtasks: ['Lägg in tempopass', 'Lägg in återhämtningsvecka', 'Hitta maratontempo'], tips: ['Allt behöver inte gå fort.', 'Håll dig skadefri.'] },
      { title: 'Genomför maraton', xpReward: 300, subtasks: ['Tajma toppningen', 'Genomför loppet', 'Följ upp efter loppet'], tips: ['Lita på din träning.', 'Håll igen i början av loppet.'] },
    ],
    quests: runningSharedQuests,
  },
];
