import type { GoalTemplateSeed } from '../template-seed-types';
import { runningSharedQuests } from './training-types';

export const trainingGoalTemplates: GoalTemplateSeed[] = [
  {
    title: 'Springa 1 km',
    icon: 'walk-outline',
    subtitle: 'Träning',
    summaryDescription: 'Kom igång med löpning och klara din första kilometer utan paus.',
    detailDescription:
      'Det här målet hjälper dig att komma i gång med löpning på ett lugnt och hållbart sätt tills du klarar att springa en kilometer.',
    category: 'TRAINING',
    difficulty: 'EASY',
    goalXpReward: 120,
    totalXpReward: 420,
    color: '#73D86A',
    isPopular: true,
    details: [
      { label: 'Kategori', value: 'Träning', visibility: 'SUMMARY' },
      { label: 'Upplägg', value: 'utvecklingssteg', visibility: 'SUMMARY' },
      { label: 'Målnivå', value: '1 km löpning', visibility: 'SUMMARY' },
      { label: 'Fokus', value: 'Låg tröskel och första löpvanan', visibility: 'DETAIL' },
    ],
    milestones: [
      {
        title: 'Kom i gång',
        description: 'Väck kroppen och skapa vana med korta pass.',
        xpReward: 60,
        subtasks: ['Gå 15 minuter utan paus', 'Jogga 30 sekunder åt gången', 'Genomför två korta pass samma vecka'],
        tips: ['Spring långsamt från början.', 'Fokusera på vana före prestation.'],
      },
      {
        title: 'Varva gång och jogg',
        description: 'Öka tiden du joggar successivt.',
        xpReward: 80,
        subtasks: ['Jogga 1 minut och gå 1 minut', 'Upprepa intervaller i 12 minuter', 'Känn efter hur kroppen svarar'],
        tips: ['Det är helt okej att gå mellan intervallerna.', 'Målet är kontinuitet.'],
      },
      {
        title: 'Bygg första uthålligheten',
        description: 'Börja springa längre sammanhängande sträckor.',
        xpReward: 80,
        subtasks: ['Spring 500 meter utan paus', 'Spring 5 minuter sammanhängande', 'Genomför tre lugna pass under en vecka'],
        tips: ['Välj platt underlag i början.', 'Ta det lugnt även om du känner dig stark.'],
      },
      {
        title: 'Spring 1 km',
        description: 'Sätt ihop allt och spring din första kilometer.',
        xpReward: 80,
        subtasks: ['Värm upp med rask gång', 'Spring 1 km utan att stanna', 'Notera hur det kändes efter passet'],
        tips: ['Börja långsammare än du tror.', 'Se första kilometern som ett startskott.'],
      },
    ],
    quests: runningSharedQuests,
  },
  {
    title: 'Springa 5 km',
    icon: 'walk-outline',
    subtitle: 'Träning',
    summaryDescription: 'Bygg upp din kondition och spring 5 km utan att stanna.',
    detailDescription:
      'Det här målet hjälper dig att bygga upp uthållighet steg för steg tills du klarar att springa 5 kilometer.',
    category: 'TRAINING',
    difficulty: 'MEDIUM',
    goalXpReward: 500,
    totalXpReward: 1200,
    color: '#73D86A',
    isPopular: true,
    details: [
      { label: 'Kategori', value: 'Träning', visibility: 'SUMMARY' },
      { label: 'Upplägg', value: 'utvecklingssteg', visibility: 'SUMMARY' },
      { label: 'Målnivå', value: '5 km löpning', visibility: 'SUMMARY' },
      { label: 'Fokus', value: 'Kondition och uthållighet', visibility: 'DETAIL' },
    ],
    milestones: [
      {
        title: 'Startmål',
        description: 'Kom igång lugnt och vänj kroppen vid rörelse.',
        xpReward: 100,
        subtasks: [
          'Gå 20 minuter utan paus',
          'Jogga 1 minut och gå 2 minuter, upprepa 8 gånger',
          'Genomför 2 lugna pass samma vecka',
        ],
        tips: [
          'Spring så långsamt att du kan prata samtidigt.',
          'Det viktigaste är att skapa vanan, inte att springa snabbt.',
        ],
      },
      {
        title: 'Grunduthållighet',
        description: 'Bygg upp konditionen så att du orkar springa längre utan att stanna.',
        xpReward: 200,
        subtasks: [
          'Spring 1 km utan paus',
          'Spring 10 minuter sammanhängande',
          'Genomför 3 träningspass under en vecka',
        ],
        tips: [
          'Varva gång och jogg om det behövs.',
          'Vila minst en dag mellan löppassen i början.',
        ],
      },
      {
        title: 'Bygg mot 5 km',
        description: 'Öka distansen stegvis och hitta ett tempo som känns hållbart.',
        xpReward: 400,
        subtasks: [
          'Spring 2 km utan paus',
          'Spring 3 km utan paus',
          'Spring 20 minuter sammanhängande',
          'Spring totalt 4 km under ett pass',
        ],
        tips: [
          'Öka hellre lite i taget än för mycket på en gång.',
          'Fokusera på att fullfölja passet, inte på hastigheten.',
        ],
      },
      {
        title: 'Nära målet',
        description: 'Ta dig från nästan där till att klara hela fem kilometer.',
        xpReward: 500,
        subtasks: [
          'Spring 4 km utan paus',
          'Spring 30 minuter sammanhängande',
          'Testa 5 km i lugnt tempo',
          'Spring 5 km utan att stanna',
        ],
        tips: [
          'Planera rutten i förväg så att du vet ungefär hur långt du ska springa.',
          'Börja långsammare än du tror att du behöver.',
        ],
      },
    ],
    quests: runningSharedQuests,
  },
  {
    title: 'Springa 10 km',
    icon: 'walk-outline',
    subtitle: 'Träning',
    summaryDescription: 'Bygg vidare från 5 km och klara att springa 10 km i ett hållbart tempo.',
    detailDescription:
      'Det här målet passar dig som redan klarar kortare distanser och vill bygga upp mer uthållighet mot 10 km.',
    category: 'TRAINING',
    difficulty: 'HARD',
    goalXpReward: 240,
    totalXpReward: 980,
    color: '#73D86A',
    isPopular: false,
    details: [
      { label: 'Kategori', value: 'Träning', visibility: 'SUMMARY' },
      { label: 'Upplägg', value: 'utvecklingssteg', visibility: 'SUMMARY' },
      { label: 'Målnivå', value: '10 km löpning', visibility: 'SUMMARY' },
      { label: 'Fokus', value: 'Distansökning, veckovolym och återhämtning', visibility: 'DETAIL' },
    ],
    milestones: [
      { title: 'Stabilisera 5 km som grund', xpReward: 120, subtasks: ['Spring 5 km två gånger', 'Hitta ett jämnt tempo', 'Återhämta dig bra mellan passen'], tips: ['Pressa inte tempot ännu.', 'Fokusera på trygg bas.'] },
      { title: 'Öka veckovolymen', xpReward: 180, subtasks: ['Lägg till ett extra pass per vecka', 'Öka total distans försiktigt', 'Logga passen du gör'], tips: ['Öka gradvis.', 'Hellre jämnt än snabbt.'] },
      { title: 'Bygg längre pass', xpReward: 220, subtasks: ['Spring 6 km', 'Spring 7 km', 'Spring 8 km i lugnt tempo'], tips: ['Välj ett kontrollerat tempo.', 'Planera återhämtning.'] },
      { title: 'Nå 10 km', xpReward: 220, subtasks: ['Spring 9 km sammanhängande', 'Testa 10 km i lugnt tempo', 'Spring 10 km utan att stanna'], tips: ['Starta lugnt.', 'Ta med vatten om passet blir långt.'] },
    ],
    quests: runningSharedQuests,
  },
  {
    title: 'Bygga muskler',
    icon: 'barbell-outline',
    subtitle: 'Träning',
    summaryDescription: 'Träna regelbundet och bygg styrka över tid.',
    detailDescription:
      'Målet fokuserar på att skapa kontinuitet i styrketräningen, sätta kostramar och följa din utveckling över tid.',
    category: 'TRAINING',
    difficulty: 'MEDIUM',
    goalXpReward: 150,
    totalXpReward: 550,
    color: '#F5C13C',
    isPopular: true,
    details: [
      { label: 'Kategori', value: 'Träning', visibility: 'SUMMARY' },
      { label: 'Upplägg', value: 'utvecklingssteg', visibility: 'SUMMARY' },
      { label: 'Fokus', value: 'Progressiv överbelastning och uppföljning', visibility: 'DETAIL' },
      { label: 'Passar dig som', value: 'vill bygga styrka och muskelmassa strukturerat', visibility: 'DETAIL' },
    ],
    milestones: [
      { title: 'Skapa ett träningsschema för veckan', xpReward: 40 },
      { title: 'Sätt mål för kost och proteinintag', xpReward: 50 },
      { title: 'Träna 3 styrkepass i veckan', xpReward: 100 },
      { title: 'Öka belastningen gradvis', xpReward: 100 },
      { title: 'Följ upp styrka och kroppsmått', xpReward: 110 },
    ],
  },
  {
    title: 'Springa halvmaraton',
    icon: 'walk-outline',
    subtitle: 'Träning',
    summaryDescription: 'Träna stegvis för att kunna genomföra ett halvmaraton.',
    detailDescription:
      'Målet guidar dig genom ett längre löparupplägg där du successivt ökar volym, långpass och återhämtning inför loppet.',
    category: 'TRAINING',
    difficulty: 'EPIC',
    goalXpReward: 300,
    totalXpReward: 1200,
    color: '#73D86A',
    isPopular: false,
    details: [
      { label: 'Kategori', value: 'Träning', visibility: 'SUMMARY' },
      { label: 'Upplägg', value: 'utvecklingssteg', visibility: 'SUMMARY' },
      { label: 'Målnivå', value: 'Halvmaraton', visibility: 'SUMMARY' },
      { label: 'Fokus', value: 'Långpass, veckovolym och återhämtning', visibility: 'DETAIL' },
      { label: 'Passar dig som', value: 'redan springer regelbundet och vill ta nästa steg', visibility: 'DETAIL' },
    ],
    milestones: [
      { title: 'Skapa ett 12-veckors träningsupplägg', xpReward: 100 },
      { title: 'Bygg upp veckovolymen gradvis', xpReward: 150 },
      { title: 'Lägg in ett långpass varje vecka', xpReward: 175 },
      { title: 'Träna tempo och återhämtning', xpReward: 175 },
      { title: 'Genomför loppet', xpReward: 300 },
    ],
    quests: runningSharedQuests,
  },
  {
    title: 'Springa maraton',
    icon: 'walk-outline',
    subtitle: 'Träning',
    summaryDescription: 'Bygg upp kroppen och rutinerna för att klara ett helt maraton.',
    detailDescription:
      'Det här är ett långt main quest för dig som vill genomföra ett maraton med struktur, tålamod och tydlig progression.',
    category: 'TRAINING',
    difficulty: 'LEGENDARY',
    goalXpReward: 500,
    totalXpReward: 1800,
    color: '#73D86A',
    isPopular: false,
    details: [
      { label: 'Kategori', value: 'Träning', visibility: 'SUMMARY' },
      { label: 'Upplägg', value: 'utvecklingssteg', visibility: 'SUMMARY' },
      { label: 'Målnivå', value: 'Maraton', visibility: 'SUMMARY' },
      { label: 'Fokus', value: 'Långsiktigt upplägg, återhämtning och långpass', visibility: 'DETAIL' },
    ],
    milestones: [
      { title: 'Sätt ett maratonupplägg', xpReward: 180, subtasks: ['Planera träningsveckor', 'Bestäm tidsram', 'Boka in nyckelpass'], tips: ['Ha marginaler i planen.', 'Utgå från din nuvarande nivå.'] },
      { title: 'Bygg stabil veckovolym', xpReward: 260, subtasks: ['Spring regelbundet varje vecka', 'Öka distans långsamt', 'Följ upp återhämtning'], tips: ['Volym kräver tålamod.', 'Hoppa inte över vila.'] },
      { title: 'Utveckla långpassen', xpReward: 320, subtasks: ['Spring 18 km', 'Spring 24 km', 'Spring 30 km'], tips: ['Långpass ska vara kontrollerade.', 'Testa energi och vätska.'] },
      { title: 'Träna fart och uthållighet', xpReward: 240, subtasks: ['Lägg in tempopass', 'Lägg in återhämtningsvecka', 'Hitta maratontempo'], tips: ['Allt behöver inte gå fort.', 'Håll dig skadefri.'] },
      { title: 'Genomför maraton', xpReward: 300, subtasks: ['Tajma toppningen', 'Genomför loppet', 'Följ upp efter loppet'], tips: ['Lita på din träning.', 'Håll igen i början av loppet.'] },
    ],
    quests: runningSharedQuests,
  },
];
