import { StyleSheet } from 'react-native';

export const goalsScreenStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#090E16' },
  container: { flex: 1, backgroundColor: '#090E16' },
  content: { paddingBottom: 120, paddingHorizontal: 16 },
  rewardBanner: {
    alignItems: 'center',
    backgroundColor: '#8B4EF4',
    borderRadius: 18,
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
    marginTop: 4,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  rewardBannerText: { flex: 1 },
  rewardBannerTitle: { color: '#F7F3FF', fontSize: 15, fontWeight: '800' },
  rewardBannerSubtitle: { color: '#F2E8FF', fontSize: 12, marginTop: 2 },
  feedbackState: { alignItems: 'center', flex: 1, justifyContent: 'center', paddingHorizontal: 24 },
  feedbackTitle: { color: '#F5F7FB', fontSize: 24, fontWeight: '700', marginTop: 18 },
  feedbackText: { color: '#97A0AE', fontSize: 14, lineHeight: 22, marginTop: 12, textAlign: 'center' },
  feedbackError: { color: '#C7CDD7', fontSize: 13, marginTop: 16, textAlign: 'center' },
  retryButton: {
    backgroundColor: '#8B4EF4',
    borderRadius: 12,
    marginTop: 24,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  retryButtonText: { color: '#F7F3FF', fontSize: 14, fontWeight: '700' },
  topBar: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 14,
    marginTop: 18,
  },
  screenTitle: { color: '#F5F7FB', fontSize: 30, fontWeight: '800' },
  addButton: {
    alignItems: 'center',
    backgroundColor: '#8B4EF4',
    borderRadius: 16,
    height: 52,
    justifyContent: 'center',
    width: 52,
  },
  tabRow: { flexDirection: 'row', marginBottom: 16 },
  tabButton: { flex: 1, paddingBottom: 12 },
  tabText: { color: '#758093', fontSize: 16, fontWeight: '700', textAlign: 'center' },
  tabTextActive: { color: '#B77BFF' },
  tabIndicator: { backgroundColor: '#202938', borderRadius: 99, height: 2, marginTop: 12 },
  tabIndicatorActive: { backgroundColor: '#A866FF' },
  filterRow: { gap: 18, paddingBottom: 10, paddingTop: 2 },
  filterItem: { alignItems: 'center', width: 68 },
  filterIconWrap: {
    alignItems: 'center',
    backgroundColor: '#121824',
    borderRadius: 16,
    height: 52,
    justifyContent: 'center',
    width: 52,
  },
  filterIconWrapActive: { backgroundColor: '#1E1930' },
  filterText: { color: '#9AA3B2', fontSize: 12, marginTop: 10, textAlign: 'center' },
  filterTextActive: { color: '#F5F7FB', fontWeight: '700' },
  sectionHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12, marginTop: 10 },
  sectionTitle: { color: '#F5F7FB', fontSize: 20, fontWeight: '800', marginBottom: 10, marginTop: 10 },
  overviewCard: {
    backgroundColor: '#141B26',
    borderColor: '#202938',
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    padding: 18,
  },
  overviewItem: { minWidth: '30%', width: '30%' },
  overviewValue: { color: '#F5F7FB', fontSize: 24, fontWeight: '800', marginTop: 8 },
  overviewLabel: { color: '#97A0AE', fontSize: 13, lineHeight: 18, marginTop: 4 },
  goalsSectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
    marginTop: 12,
  },
  emptyGoalsCard: {
    alignItems: 'center',
    backgroundColor: '#141B26',
    borderColor: '#202938',
    borderRadius: 24,
    borderWidth: 1,
    marginTop: 8,
    padding: 24,
  },
  emptyGoalsTitle: { color: '#F5F7FB', fontSize: 22, fontWeight: '800', marginTop: 12 },
  emptyGoalsText: { color: '#97A0AE', fontSize: 14, lineHeight: 22, marginTop: 10, textAlign: 'center' },
  emptyGoalsButton: {
    backgroundColor: '#8B4EF4',
    borderRadius: 12,
    marginTop: 18,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  emptyGoalsButtonText: { color: '#F7F3FF', fontSize: 14, fontWeight: '700' },
  goalCard: {
    backgroundColor: '#141B26',
    borderColor: '#202938',
    borderRadius: 22,
    borderWidth: 1,
    marginBottom: 16,
    padding: 18,
  },
  goalHeader: { alignItems: 'center', flexDirection: 'row', gap: 14 },
  goalIconWrap: {
    alignItems: 'center',
    borderRadius: 18,
    height: 56,
    justifyContent: 'center',
    width: 56,
  },
  goalHeaderText: { flex: 1 },
  goalTitle: { color: '#F5F7FB', fontSize: 18, fontWeight: '800' },
  goalSubtitle: { color: '#B5BECC', fontSize: 14, marginTop: 4 },
  goalDifficulty: { color: '#97A0AE', fontSize: 12, marginTop: 6 },
  goalPercent: { color: '#F5F7FB', fontSize: 16, fontWeight: '800' },
  progressTrack: {
    backgroundColor: '#2A3342',
    borderRadius: 999,
    height: 8,
    marginTop: 16,
    overflow: 'hidden',
  },
  progressFill: { borderRadius: 999, height: '100%' },
  metaRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 12 },
  metaText: { color: '#A9B3C2', fontSize: 13, fontWeight: '600' },
  confirmBackdrop: { backgroundColor: 'rgba(4, 8, 16, 0.78)', flex: 1, justifyContent: 'center', padding: 24 },
  confirmCard: {
    backgroundColor: '#121925',
    borderColor: '#242D3D',
    borderRadius: 24,
    borderWidth: 1,
    padding: 22,
  },
  confirmTitle: { color: '#F5F7FB', fontSize: 22, fontWeight: '800' },
  confirmText: { color: '#9AA4B3', fontSize: 14, lineHeight: 22, marginTop: 10 },
  confirmActions: { flexDirection: 'row', gap: 12, justifyContent: 'flex-end', marginTop: 20 },
  confirmButtonSecondary: {
    backgroundColor: '#1B2432',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  confirmButtonSecondaryText: { color: '#D9E0EA', fontSize: 14, fontWeight: '700' },
  confirmButtonPrimary: {
    backgroundColor: '#8B4EF4',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  confirmButtonPrimaryText: { color: '#F7F3FF', fontSize: 14, fontWeight: '700' },
});
