import { CATEGORY_COLORS, type GoalTemplateSeed } from '../template-seed-types';

export const socialGoalTemplates: GoalTemplateSeed[] = [
  {
    title: 'Stärka relationen med partnern',
    icon: 'heart-outline',
    subtitle: ['social'],
    summaryDescription: 'Skapa mer kvalitetstid, bättre kommunikation och tydliga vanor tillsammans.',
    category: 'RELATIONSHIP',
    difficulty: 'MEDIUM',
    focusLabel: 'Partnerrelation',
    totalXpReward: 760,
    color: CATEGORY_COLORS.social,
    isPopular: true,
    milestones: [
      { title: 'Prata om vad ni båda vill förbättra' },
      { title: 'Planera in regelbunden kvalitetstid' },
      { title: 'Skapa bättre vanor för kommunikation' },
      { title: 'Följ upp hur det känns efter två veckor' },
      { title: 'Justera gemensamma rutiner' },
    ],
  },
  {
    title: 'Utöka mitt sociala nätverk',
    icon: 'people-outline',
    subtitle: ['social'],
    summaryDescription: 'Bygg fler meningsfulla relationer i vardagen.',
    category: 'RELATIONSHIP',
    difficulty: 'MEDIUM',
    focusLabel: 'Nya sociala kontakter',
    totalXpReward: 760,
    color: CATEGORY_COLORS.social,
    isPopular: false,
    milestones: [
      { title: 'Identifiera sammanhang där du kan träffa nya personer' },
      { title: 'Ta initiativ till en ny social aktivitet' },
      { title: 'Håll kontakt med minst två nya personer' },
      { title: 'Boka in en uppföljande träff eller fika' },
      { title: 'Bygg en återkommande social rutin' },
    ],
  },
  {title: 'Förbättra relationen med familjen',
    icon: 'home-outline',
    subtitle: ['social'],
    summaryDescription: 'Skapa mer kvalitetstid, bättre kommunikation och tydliga vanor tillsammans.',
    category: 'RELATIONSHIP',
    difficulty: 'MEDIUM',
    focusLabel: 'Familjerelationer',
    totalXpReward: 680,
    color: CATEGORY_COLORS.social,
    isPopular: true,
    milestones: [
      { title: 'Prata om vad ni vill förbättra i relationen' },
      { title: 'Planera in regelbunden kvalitetstid tillsammans' },
      { title: 'Skapa bättre vanor för kommunikation' },
      { title: 'Justera gemensamma rutiner' }, 
    ],
  },
];
