import { StyleSheet } from 'react-native';

export const editGoalStyles = StyleSheet.create({
  inlineErrorCard: {
    alignItems: 'center',
    backgroundColor: '#2A1D1D',
    borderColor: '#5C3030',
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    marginHorizontal: 20,
    marginTop: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  inlineErrorText: {
    color: '#F8D0D0',
    flex: 1,
    fontSize: 13,
    lineHeight: 18,
  },
  detailCard: {
    backgroundColor: '#101B2A',
    borderColor: '#243246',
    borderRadius: 24,
    borderWidth: 1,
    marginHorizontal: 20,
    marginTop: 18,
    overflow: 'hidden',
    padding: 22,
  },
  heroCard: {
    minHeight: 258,
    padding: 0,
    position: 'relative',
  },
  heroBackground: {
    borderRadius: 24,
    overflow: 'hidden',
  },
  heroBackgroundImage: {
    opacity: 0.2,
  },
  heroOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(7, 16, 28, 0.72)',
  },
  detailHeroRow: {
    flexDirection: 'row',
    gap: 18,
    minHeight: 214,
    justifyContent: 'space-between',
  },
  detailHeroLeft: {
    flex: 1,
    flexDirection: 'row',
    gap: 18,
  },
  detailHeroIconWrap: {
    alignItems: 'center',
    borderRadius: 28,
    height: 108,
    justifyContent: 'center',
    width: 108,
  },
  detailHeroCopy: {
    flex: 1,
    justifyContent: 'flex-start',
    paddingTop: 10,
  },
  heroTitleInput: {
    color: '#F7F9FC',
    fontSize: 31,
    fontWeight: '800',
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  detailMetaPills: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 10,
    marginTop: 10,
  },
  heroDifficultyPill: {
    backgroundColor: '#8B4EF4',
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  heroDifficultyPillText: {
    color: '#F7F3FF',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.4,
  },
  detailXpBadge: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(19, 26, 37, 0.86)',
    borderColor: '#7D5AC6',
    borderRadius: 24,
    borderWidth: 1,
    minWidth: 178,
    paddingHorizontal: 18,
    paddingVertical: 22,
  },
  detailXpBadgeValue: {
    color: '#F5F7FB',
    fontSize: 24,
    fontWeight: '800',
    marginTop: 10,
  },
  detailXpBadgeLabel: {
    color: '#E6EAF0',
    fontSize: 11,
    fontWeight: '700',
    marginTop: 6,
    textAlign: 'center',
  },
  heroCategoryRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 28,
  },
  heroCategoryBadge: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  heroCategoryDot: {
    backgroundColor: '#A866FF',
    borderRadius: 999,
    height: 16,
    width: 16,
  },
  heroCategoryText: {
    color: '#F2F5FA',
    fontSize: 17,
    fontWeight: '600',
  },
  detailCardTitle: {
    color: '#F5F7FB',
    fontSize: 22,
    fontWeight: '800',
    marginBottom: 18,
  },
  overviewGrid: {
    flexDirection: 'row',
  },
  overviewGridItem: {
    flex: 1,
    minHeight: 126,
    paddingHorizontal: 18,
  },
  overviewGridDivider: {
    borderRightColor: '#253144',
    borderRightWidth: 1,
  },
  detailRowIconWrap: {
    alignItems: 'center',
    backgroundColor: '#341E59',
    borderRadius: 22,
    height: 52,
    justifyContent: 'center',
    marginBottom: 18,
    width: 52,
  },
  detailLabel: {
    color: '#D4D9E2',
    fontSize: 13,
    marginBottom: 10,
  },
  overviewGridValue: {
    color: '#F5F7FB',
    fontSize: 17,
    fontWeight: '800',
    lineHeight: 22,
  },
  milestonesHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  addIconButton: {
    alignItems: 'center',
    backgroundColor: '#7B3FE6',
    borderColor: '#B28BFF',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 16,
    paddingVertical: 11,
  },
  addIconButtonText: {
    color: '#F7F3FF',
    fontSize: 15,
    fontWeight: '700',
  },
  timelineList: {
    marginTop: 8,
    paddingLeft: 8,
  },
  milestoneEditorCard: {
    minHeight: 94,
    paddingLeft: 30,
    position: 'relative',
  },
  timelineLine: {
    backgroundColor: '#7B3FE6',
    left: 18,
    opacity: 0.65,
    position: 'absolute',
    top: 48,
    width: 2,
    bottom: -8,
  },
  milestoneEditorRow: {
    alignItems: 'center',
    borderTopColor: '#223043',
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 14,
    minHeight: 82,
  },
  milestoneEditorHeader: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 16,
    paddingVertical: 10,
  },
  milestoneIndexWrap: {
    alignItems: 'center',
    backgroundColor: '#47247C',
    borderColor: '#B587FF',
    borderRadius: 22,
    borderWidth: 1,
    height: 42,
    justifyContent: 'center',
    left: -30,
    position: 'absolute',
    width: 42,
  },
  milestoneIndexText: {
    color: '#FFF7FF',
    fontSize: 20,
    fontWeight: '800',
  },
  milestoneMetaIconWrap: {
    alignItems: 'center',
    borderRadius: 18,
    height: 56,
    justifyContent: 'center',
    width: 56,
  },
  milestoneTextWrap: {
    flex: 1,
  },
  milestoneEditorHeaderText: {
    color: '#F5F7FB',
    fontSize: 18,
    fontWeight: '800',
  },
  milestoneDescription: {
    color: '#D0D6DF',
    fontSize: 13,
    lineHeight: 18,
    marginTop: 4,
  },
  milestoneXpValue: {
    color: '#F7E8FF',
    fontSize: 15,
    fontWeight: '800',
  },
  milestoneXpBadge: {
    backgroundColor: '#563083',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  trashButton: {
    paddingHorizontal: 6,
    paddingVertical: 8,
  },
  stickyFooter: {
    backgroundColor: '#090E16',
    borderTopColor: '#171D28',
    borderTopWidth: 1,
    bottom: 0,
    paddingBottom: 18,
    paddingHorizontal: 20,
    paddingTop: 14,
    position: 'absolute',
    width: '100%',
  },
  addGoalButton: {
    alignItems: 'center',
    backgroundColor: '#9A5CF8',
    borderRadius: 18,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
    paddingVertical: 18,
  },
  addGoalButtonDisabled: {
    opacity: 0.6,
  },
  addGoalButtonText: {
    color: '#F7F3FF',
    fontSize: 17,
    fontWeight: '800',
  },
  questCollapseButton: {
    alignItems: 'center',
    backgroundColor: '#141D2A',
    borderColor: '#243144',
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 18,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  questCollapseLabelRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  questCollapseButtonText: {
    color: '#E4E9F1',
    fontSize: 14,
    fontWeight: '700',
  },
  questPreviewBox: {
    backgroundColor: '#121925',
    borderColor: '#223043',
    borderRadius: 16,
    borderWidth: 1,
    marginTop: 12,
    overflow: 'hidden',
  },
  questPreviewRow: {
    alignItems: 'center',
    borderTopColor: '#202B3B',
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  questPreviewInfo: {
    flex: 1,
  },
  questPreviewTitle: {
    color: '#F5F7FB',
    fontSize: 14,
    fontWeight: '700',
  },
  questPreviewText: {
    color: '#AAB4C2',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 4,
  },
  questPreviewMeta: {
    alignItems: 'flex-end',
    gap: 6,
  },
  questPreviewFrequency: {
    color: '#AAB4C2',
    fontSize: 11,
    fontWeight: '700',
  },
  questPreviewXp: {
    color: '#E8D8FF',
    fontSize: 13,
    fontWeight: '800',
  },
  modalBackdrop: {
    backgroundColor: 'rgba(6, 10, 16, 0.78)',
    flex: 1,
    justifyContent: 'center',
    padding: 18,
  },
  modalCard: {
    backgroundColor: '#101826',
    borderColor: '#243246',
    borderRadius: 24,
    borderWidth: 1,
    maxHeight: '82%',
    padding: 20,
  },
  modalHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  modalTitle: {
    color: '#F5F7FB',
    fontSize: 22,
    fontWeight: '800',
  },
  input: {
    backgroundColor: '#121D2B',
    borderColor: '#243246',
    borderRadius: 14,
    borderWidth: 1,
    color: '#F5F7FB',
    fontSize: 14,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  secondaryInput: {
    marginTop: 12,
  },
  modalSectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 18,
  },
  editorSectionTitle: {
    color: '#F5F7FB',
    fontSize: 16,
    fontWeight: '800',
  },
  inlineActionText: {
    color: '#B88BFF',
    fontSize: 13,
    fontWeight: '800',
  },
  inlineEditorRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    marginTop: 10,
  },
  inlineInput: {
    flex: 1,
  },
});
